<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/infobanner/localization/<lang>.inc                            |
 |                                                                       |
 | Localization file of the Roundcube Webmail InfoBanner plugin          |
 | Copyright (C) 2013, dharman                                           |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/

$labels = array();
$labels['spamExpiration'] = 'Los mensajes que se encuentren en Spam durante más de 30 días se eliminarán automáticamente';

?>
