<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/infobanner/localization/<lang>.inc                            |
 |                                                                       |
 | Localization file of the Roundcube Webmail InfoBanner plugin          |
 | Copyright (C) 2013, dharman                                           |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/

$labels = array();
$labels['spamExpiration'] = 'I messaggi in Spam che risalgono a più di 30 giorni verranno eliminati automaticamente';

?>